defaults: &defaults
  docker:
    - image: opuscapita/minsk-core-ci:grails-2.4.4-jdk-8u131-nodejs-8.9.4-maven-3.3.9
  working_directory: ~/build

version: 2
jobs:
  release:
    <<: *defaults
    steps:
      - run:
          name: Environment inject
          command: env_inject.sh

      - checkout

      - run:
          name: Executing release script.
          command: release.sh node
workflows:
  version: 2
  release-and-build:
    jobs:
      - release:
          filters:
            branches:
              ignore: